Quiz
mimi-net/miminet pull request #74
Opened 2024-03-16 22:58 UTC by ElenaBakova

2024-03-19 13:27 UTC, i1ya commented on back/src/pkt_parser.py
Ты видимо не от последней версии сделала ветку.
В back/src/pkt_parser.py не нужны твои старые изменения.

Убери их.

2024-03-19 13:30 UTC, i1ya commented on front/src/app.py
Ты разве используешь где-то 
create_section_endpoint,  create_test_endpoint, get_deleted_tests_by_owner_endpoint и подобные эндпоинты? Мы же пока через админку все сделали, не?

2024-03-19 13:33 UTC, i1ya commented on front/src/miminet_config.py
Опять.
Это ты правила или это просто старый код?

2024-03-19 13:33 UTC, i1ya commented on front/src/miminet_host.py
Тут тоже.
Кто-то отформатировал код.

2024-03-19 13:40 UTC, i1ya requested changes
Я оставил комментарии.
Разберись с ними и присылай еще раз.

2024-03-19 20:30 UTC, ElenaBakova commented on back/src/pkt_parser.py
Это изменения линтера, форкала от последней версии на тот момент

2024-03-19 21:55 UTC, ElenaBakova commented on front/src/miminet_config.py
Тут случайно, верну назад

2024-03-19 21:55 UTC, ElenaBakova commented on front/src/miminet_host.py
Это тоже линтер как я понимаю

2024-03-19 22:00 UTC, ElenaBakova commented on front/src/app.py
Убрала

2024-03-20 11:23 UTC, i1ya approved these changes

2024-03-20 11:42 UTC, merged